version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wealthwise
      POSTGRES_USER: wealthwise
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wealthwise"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://wealthwise:password@db:5432/wealthwise
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - AES_ENCRYPTION_KEY=your-32-byte-base64-encoded-encryption-key
      - ALPHA_VANTAGE_API_KEY=your-alpha-vantage-api-key
      - COINGECKO_API_KEY=your-coingecko-api-key
      - VITE_API_BASE_URL=http://localhost:3000
      - APP_NAME=WealthWise
      - APP_VERSION=1.0.0
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting server...' &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
